# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "deps: "
      prefix-development: "deps: "

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "deps: "
      prefix-development: "deps: "

  - package-ecosystem: uv
    directory: /benchmark/fraise
    schedule:
      interval: daily
    commit-message:
      prefix: "deps: "
      prefix-development: "deps: "

  - package-ecosystem: uv
    directory: /benchmark/graphiti
    schedule:
      interval: daily
    commit-message:
      prefix: "deps: "
      prefix-development: "deps: "

  - package-ecosystem: uv
    directory: /benchmark/letta
    schedule:
      interval: daily
    commit-message:
      prefix: "deps: "
      prefix-development: "deps: "

  - package-ecosystem: uv
    directory: /benchmark/mem0
    schedule:
      interval: daily
    commit-message:
      prefix: "deps: "
      prefix-development: "deps: "
