[project]
name = "cognee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "René-Jean Corneille", email = "corneille.r.j@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "amb",
    "cognee[neo4j,postgres-binary]>=1.5,<1.6",
]

[project.entry-points."amb.systems"]
cognee = "src.benchmark:CogneeBenchmark"

[tool.uv.sources]
amb = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]
